### ISSUE TITLE
Some details 

### ISSUE THREAD

**Issue by Jasper0420** [xyl-507/QRDT#2]
Thank you for your excellent contribution to the drone community! Your article was very inspiring for me!
But I'm confused with some minor questions.
First of all, is this article not yet publicized above IEEE and I can't retrieve him, which prevents me from reading the details of it! It's a pity!
Secondly, I would like to inquire that in single target tracking, when objects are full-occluded I see a lot of annotations are Nan or wrong, such as the bike2 sequence in uav123, etc., and in lasot a lot of objects that are full-occluded have GTs that are wrong and still stay in the previous frame. Also, I noticed that in the tracked dataloader it seems like the full-occlusion frames are not sampled. That is to say, in the sequence of full-occlusion attributes, which occluded frames are not actually included inside the sequence input to the tracker. But in the test these frames are input to the model (regardless of whether the object is fully occluded or not), so when calculating the precision, does it mean that these frames where the object is fully-occluded are not involved in the precision calculation (because their own GT is wrong). Then in the problem of calculating occlusion, it's still essentially a matter of an object transiently moving from one fast disappearing position to another (since the intervening frames that are fully-occluded are not sampled/do not participate in the calculation of Pr).
Thanks for wishing well!
感谢您对无人机社区做的卓越的贡献！你的文章对我来说非常的有启发！
但是我有一些小问题很困惑。
首先，这篇文章是不是还未在IEEE上面公开，我检索不到他，导致我不能阅读其中的细节！很遗憾！
其次，我想咨询一下在单目标跟踪中，当物体full-occlusion的时候我看很多的注释是Nan或者是错误的，例如uav123中的bike2序列等等，而在lasot中很多被full-occlusion的物体GT是错误的，仍然停留在上一帧。此外，我注意到在跟踪的dataloader中好像full-occlusion的帧是不被sample的。也就是说，在full-occlusion属性的序列中，其实输入到跟踪器的序列里面不包含哪些被遮挡的帧。但是在测试中这些帧是输入进模型的（无论物体是否被完全遮挡），那么在计算精度的时候，是否代表着这些物体被full-occlusion的帧不参与精度的计算（因为他们本身的GT就是错误的）。那么在计算遮挡的问题中，本质上还是一个物体从某一个快消失的位置瞬移到另外一个位置（因为中间完全被遮挡的帧未被采样/不参与计算Pr）。
感谢祝好！

**Comment by xyl-507** [comment]
感谢你的关注。
1.我们的文章已经被录用，但还没出版
2.不同的评测工具箱（pysot、pytracking）处理无效帧的方式是不同的。可以参考：https://github.com/visionml/pytracking/issues/87

**Comment by Jasper0420** [comment]
好的，感谢解答！
方便留个联系方式吗？以后还希望跟您多多请教学习！

**Comment by xyl-507** [comment]
可以把QQ发我的邮箱，xyl_507@outlook.com
